// <auto-generated />
using Auction.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Auction.Infrastructure.Migrations
{
    [DbContext(typeof(AuctionContext))]
    [Migration("20171027121449_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("Relational:Sequence:.EntityFrameworkHiLoSequence", "'EntityFrameworkHiLoSequence', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Auction.Domain.Auction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Auction");
                });

            modelBuilder.Entity("Auction.Domain.AuctionItem", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid?>("AuctionId")
                        .IsRequired();

                    b.Property<string>("Description");

                    b.Property<int>("Id");

                    b.Property<string>("Name");

                    b.Property<decimal?>("ReservedPrice");

                    b.HasKey("UniqueId");

                    b.HasAlternateKey("Id", "AuctionId")
                        .HasName("AlternateKey_itemId_auctionId");

                    b.HasIndex("AuctionId");

                    b.ToTable("Auction_Items");
                });

            modelBuilder.Entity("Auction.Domain.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:HiLoSequenceName", "EntityFrameworkHiLoSequence")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<decimal>("Amount");

                    b.Property<Guid?>("AuctionItemUniqueId");

                    b.Property<DateTime>("BidTimestamp");

                    b.Property<string>("Bidder");

                    b.HasKey("Id");

                    b.HasIndex("AuctionItemUniqueId");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("Auction.Infrastructure.EntitiesConfigurations.IntegrationEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Payload")
                        .HasMaxLength(2147483647);

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("Id");

                    b.ToTable("Integration_events_queue");
                });

            modelBuilder.Entity("Auction.Domain.AuctionItem", b =>
                {
                    b.HasOne("Auction.Domain.Auction")
                        .WithMany("Items")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Auction.Domain.Bid", b =>
                {
                    b.HasOne("Auction.Domain.AuctionItem")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionItemUniqueId");
                });
#pragma warning restore 612, 618
        }
    }
}
