using Auction.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Auction.Infrastructure.EntitiesConfigurations
{
    public class BidEntityConfiguration : IEntityTypeConfiguration<Domain.Bid>
    {
        public void Configure(EntityTypeBuilder<Bid> builder)
        {
            //builder.Property("AuctionItemId").HasColumnType("UNIQUEIDENTIFIER").IsRequired(); //TODO: check if auto generated by ef, in case not need to add

            builder.Property<int>("Id").HasColumnType("int").ValueGeneratedOnAdd().ForSqlServerUseSequenceHiLo();

            builder.HasKey("Id");
            // identity running int as primary key?
        }
    }
}